// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SafePoint_IRS.Data;

#nullable disable

namespace SafePoint_IRS.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251124083218_AllowAdminModCommentsAndSuspension")]
    partial class AllowAdminModCommentsAndSuspension
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SafePoint_IRS.Models.Admin", b =>
                {
                    b.Property<Guid>("Adminid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Adminpassword")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("APassword");

                    b.Property<string>("Contact")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("SuspensionEndTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserRole")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Adminid");

                    b.ToTable("Admin", (string)null);
                });

            modelBuilder.Entity("SafePoint_IRS.Models.Area", b =>
                {
                    b.Property<string>("Area_Code")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("ALocation")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("ALocation");

                    b.HasKey("Area_Code");

                    b.ToTable("Area", (string)null);
                });

            modelBuilder.Entity("SafePoint_IRS.Models.Comment", b =>
                {
                    b.Property<decimal>("Comment_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric(18,0)");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<decimal>("Comment_ID"));

                    b.Property<Guid?>("AdminId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("IncidentID")
                        .HasColumnType("int");

                    b.Property<Guid?>("ModId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("Userid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("comment")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("dttm")
                        .HasColumnType("datetime2");

                    b.HasKey("Comment_ID");

                    b.HasIndex("AdminId");

                    b.HasIndex("IncidentID");

                    b.HasIndex("ModId");

                    b.HasIndex("Userid");

                    b.ToTable("Comment", (string)null);
                });

            modelBuilder.Entity("SafePoint_IRS.Models.IType", b =>
                {
                    b.Property<string>("Incident_Code")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Incident_Type")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Incident_Code");

                    b.ToTable("IType", (string)null);
                });

            modelBuilder.Entity("SafePoint_IRS.Models.Incident", b =>
                {
                    b.Property<int>("IncidentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IncidentID"));

                    b.Property<string>("Area_Code")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descr")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("Img")
                        .HasColumnType("varbinary(max)");

                    b.Property<DateTime>("IncidentDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Incident_Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal?>("Latitude")
                        .HasColumnType("decimal(10,8)");

                    b.Property<string>("LocationAddress")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<decimal?>("Longitude")
                        .HasColumnType("decimal(11,8)");

                    b.Property<string>("OtherHazard")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<Guid>("Userid")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("IncidentID");

                    b.HasIndex("Area_Code");

                    b.HasIndex("Incident_Code");

                    b.HasIndex("Userid");

                    b.ToTable("Incident", (string)null);
                });

            modelBuilder.Entity("SafePoint_IRS.Models.Moderator", b =>
                {
                    b.Property<Guid>("Modid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Area_Code")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Contact")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Modpassword")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("MPassword");

                    b.Property<DateTime?>("SuspensionEndTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserRole")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Modid");

                    b.HasIndex("Area_Code");

                    b.ToTable("Moderator", (string)null);
                });

            modelBuilder.Entity("SafePoint_IRS.Models.RejectedIncident", b =>
                {
                    b.Property<int>("RejectedIncidentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RejectedIncidentID"));

                    b.Property<string>("Area_Code")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descr")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("Img")
                        .HasColumnType("varbinary(max)");

                    b.Property<DateTime>("IncidentDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Incident_Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal?>("Latitude")
                        .HasColumnType("decimal(10,8)");

                    b.Property<string>("LocationAddress")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<decimal?>("Longitude")
                        .HasColumnType("decimal(11,8)");

                    b.Property<int>("OriginalIncidentID")
                        .HasColumnType("int");

                    b.Property<string>("OtherHazard")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("RejectionDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<Guid>("Userid")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("RejectedIncidentID");

                    b.HasIndex("Area_Code");

                    b.HasIndex("Incident_Code");

                    b.HasIndex("Userid");

                    b.ToTable("RejectedIncidents");
                });

            modelBuilder.Entity("SafePoint_IRS.Models.User", b =>
                {
                    b.Property<Guid>("Userid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Contact")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("SuspensionEndTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserRole")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Userpassword")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Userid");

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("SafePoint_IRS.Models.Valid", b =>
                {
                    b.Property<string>("Validation_ID")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("IncidentID")
                        .HasColumnType("int");

                    b.Property<DateTime?>("Validation_Date")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Validation_Status")
                        .HasColumnType("bit");

                    b.HasKey("Validation_ID");

                    b.HasIndex("IncidentID")
                        .IsUnique();

                    b.ToTable("Valid", (string)null);
                });

            modelBuilder.Entity("SafePoint_IRS.Models.Comment", b =>
                {
                    b.HasOne("SafePoint_IRS.Models.Admin", "Admin")
                        .WithMany()
                        .HasForeignKey("AdminId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SafePoint_IRS.Models.Incident", "Incident")
                        .WithMany("Comments")
                        .HasForeignKey("IncidentID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SafePoint_IRS.Models.Moderator", "Moderator")
                        .WithMany()
                        .HasForeignKey("ModId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SafePoint_IRS.Models.User", "User")
                        .WithMany("Comments")
                        .HasForeignKey("Userid")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Admin");

                    b.Navigation("Incident");

                    b.Navigation("Moderator");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SafePoint_IRS.Models.Incident", b =>
                {
                    b.HasOne("SafePoint_IRS.Models.Area", "Area")
                        .WithMany("Incidents")
                        .HasForeignKey("Area_Code")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SafePoint_IRS.Models.IType", "IType")
                        .WithMany("Incidents")
                        .HasForeignKey("Incident_Code")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SafePoint_IRS.Models.User", "User")
                        .WithMany("Incidents")
                        .HasForeignKey("Userid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Area");

                    b.Navigation("IType");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SafePoint_IRS.Models.Moderator", b =>
                {
                    b.HasOne("SafePoint_IRS.Models.Area", "Area")
                        .WithMany("Moderators")
                        .HasForeignKey("Area_Code")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Area");
                });

            modelBuilder.Entity("SafePoint_IRS.Models.RejectedIncident", b =>
                {
                    b.HasOne("SafePoint_IRS.Models.Area", "Area")
                        .WithMany()
                        .HasForeignKey("Area_Code")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SafePoint_IRS.Models.IType", "IType")
                        .WithMany()
                        .HasForeignKey("Incident_Code")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SafePoint_IRS.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("Userid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Area");

                    b.Navigation("IType");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SafePoint_IRS.Models.Valid", b =>
                {
                    b.HasOne("SafePoint_IRS.Models.Incident", "Incident")
                        .WithOne("ValidStatus")
                        .HasForeignKey("SafePoint_IRS.Models.Valid", "IncidentID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Incident");
                });

            modelBuilder.Entity("SafePoint_IRS.Models.Area", b =>
                {
                    b.Navigation("Incidents");

                    b.Navigation("Moderators");
                });

            modelBuilder.Entity("SafePoint_IRS.Models.IType", b =>
                {
                    b.Navigation("Incidents");
                });

            modelBuilder.Entity("SafePoint_IRS.Models.Incident", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("ValidStatus");
                });

            modelBuilder.Entity("SafePoint_IRS.Models.User", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("Incidents");
                });
#pragma warning restore 612, 618
        }
    }
}
